title: Liucija | Data Scientist
email: your.email@example.com
description: >
  I build data-driven systems.
baseurl: "" # leave empty for GitHub Pages
url: "https://liucijasvink.github.io"
theme: minima